In [1]:
import numpy as np

In [13]:
#1- Create a numpy array of shape (3, 4) and assign random integers between 1 and 10 to every element.
a_array=np.random.randint(1,11,size=(3,4))
a_array

array([[ 2,  2,  2, 10],
       [ 8,  1,  4,  9],
       [ 1,  7,  5,  7]], dtype=int32)

In [14]:
#2- Find the maximum value in the array created in step 1.
np.max(a_array)

np.int32(10)

In [15]:
#3- Calculate the mean value of each row in the array.
np.mean(a_array,axis=1)

array([4. , 5.5, 5. ])

In [16]:
#4- Reshape the array from step 1 into a shape of (2, 6).
a_array.reshape(2,6)

array([[ 2,  2,  2, 10,  8,  1],
       [ 4,  9,  1,  7,  5,  7]], dtype=int32)

In [17]:
#5- Multiply each element in the array by 2.
a_array*2

array([[ 4,  4,  4, 20],
       [16,  2,  8, 18],
       [ 2, 14, 10, 14]], dtype=int32)

In [20]:
#6- Create a numpy array with values ranging from 0 to 9. Extract the odd numbers from the array.
a=np.random.randint(10,size=(3,4))
print(a)
a[a%2!=0]

[[6 8 6 0]
 [3 9 7 3]
 [9 0 2 2]]


array([3, 9, 7, 3, 9], dtype=int32)

In [21]:
#7- Create a 3x3 identity matrix using numpy.
a_array= np.identity(3,dtype='int32')
a_array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [40]:
#8- Create a 5x5 array with random values and normalize it (subtract the mean and divide by the standard deviation of the array).
a=np.random.randint(11,size=(5,5))
#print(a)
#print(np.mean(a))
b=(a-np.mean(a))/np.std(a)
b

[[ 8  3  7 10  2]
 [ 3  7  2  5  7]
 [ 5  1  3  1  8]
 [ 4  6 10  2  8]
 [ 1  2  5  6  3]]
4.76


array([[ 1.17354337, -0.63748035,  0.81133862,  1.89795285, -0.99968509],
       [-0.63748035,  0.81133862, -0.99968509,  0.08692914,  0.81133862],
       [ 0.08692914, -1.36188983, -0.63748035, -1.36188983,  1.17354337],
       [-0.2752756 ,  0.44913388,  1.89795285, -0.99968509,  1.17354337],
       [-1.36188983, -0.99968509,  0.08692914,  0.44913388, -0.63748035]])

In [43]:
#9- Perform element-wise multiplication between two arrays of the same shape.
a1=np.random.randint(11,size=(5,5))
a2=np.random.randint(11,size=(5,5))
print(a1)
print(a2)
a1*a2

[[ 4  1  1  5  0]
 [ 1 10  7  7  0]
 [ 0  8  2  7  7]
 [ 0  6  6  6  7]
 [ 5 10  2  1  6]]
[[ 1  3  6  7  3]
 [ 4  2  4  3  3]
 [ 7  2  8  0  8]
 [ 4  1  4  4  3]
 [10  0  1  3  7]]


array([[ 4,  3,  6, 35,  0],
       [ 4, 20, 28, 21,  0],
       [ 0, 16, 16,  0, 56],
       [ 0,  6, 24, 24, 21],
       [50,  0,  2,  3, 42]], dtype=int32)

In [44]:
#10 - Given an array of heights in centimeters, convert them to inches (1 inch = 2.54 cm).
a=np.random.randint(11,size=(5,5))
print(a)
ainch=a*2.54
ainch

[[0 8 1 4 8]
 [4 7 1 0 2]
 [1 0 3 8 2]
 [4 0 5 8 4]
 [3 7 6 9 1]]


array([[ 0.  , 20.32,  2.54, 10.16, 20.32],
       [10.16, 17.78,  2.54,  0.  ,  5.08],
       [ 2.54,  0.  ,  7.62, 20.32,  5.08],
       [10.16,  0.  , 12.7 , 20.32, 10.16],
       [ 7.62, 17.78, 15.24, 22.86,  2.54]])

In [47]:
#11 - Create a 1D array of numbers from 0 to 9. Replace all odd numbers with -1.
a=np.arange(10)
a[a%2!=0]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [62]:
#12 - Create a 2D array with random values and find the indices of the maximum and minimum values.
a=np.random.randint(11,size=(4,4))
print(a)
i,j=np.where(a==np.max(a))
print(f"Maximum values index : {i,j}")
i,j=np.where(a==np.min(a))
print(f"Minimum values index : {i,j}")

[[ 5  7  6  0]
 [10  2  1  4]
 [ 2 10  2  7]
 [ 2  3  5  9]]
Maximum values index : (array([1, 2]), array([0, 1]))
Minimum values index : (array([0]), array([3]))
